version: '2.0'
services:
    redis:
        image: redis:alpine
        container_name: ${DOCKER_PREFIX}_redis
        environment:
            - REDIS_PASSWORD=root
        command:
            - /bin/sh
            - -c
            - redis-server --maxmemory 128mb --maxmemory-policy volatile-lru --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}" --save ""
        volumes:
            - symfony-redis:/data
        ports:
            - ${DOCKER_IP}:${DOCKER_PORT_REDIS}:6379
    redis-commander:
        container_name: ${DOCKER_PREFIX}_redis-commander
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379:0:root
        ports:
            - ${DOCKER_IP}:${DOCKER_PORT_REDIS_COMMANDER}:8081
    db:
        image: docker.ideo.pl/docker/mirror/mysql:8.0
        container_name: ${DOCKER_PREFIX}_db
        working_dir: /application
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sort_buffer_size=512MB
        volumes:
            - symfony-database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=${DBNAME}
            - MYSQL_USER=${DBUSER}
            - MYSQL_PASSWORD=${DBPASS}
        ports:
        - "${DOCKER_IP}:${DOCKER_PORT_MYSQL}:3306"
    nginx:
        image: nginx:stable-alpine
        container_name: ${DOCKER_PREFIX}_nginx
        ports:
            - "${DOCKER_IP}:${DOCKER_PORT}:80"
            - "${DOCKER_IP}:${DOCKER_PORT_SSL}:443"
        volumes:
            - .:/var/www/html:ro
            - ./.tools/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./.tools/docker/nginx/ssl:/etc/nginx/certs:ro
        depends_on:
            - php-fpm
    php-fpm:
        image: docker.ideo.pl/pimcore/env:php8.0.1-fpm
        container_name: ${DOCKER_PREFIX}_php
        volumes:
            - .:/var/www/html:cached
            - ./.tools/docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/x-99-overrides.ini
        depends_on:
            - db
            - redis
    mailcatcher:
        image: schickling/mailcatcher
        container_name: ${DOCKER_PREFIX}_mailcatcher
        ports:
            - "${DOCKER_IP}:1080:1080"
volumes:
    symfony-database:
    symfony-redis:
